<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenFinance.Customers.Application\OpenFinance.Customers.Application.csproj" />
    <ProjectReference Include="..\OpenFinance.Customers.Infrastructure\OpenFinance.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenFinance.Customers.CrossCutting\OpenFinance.Customers.CrossCutting.csproj" />
  </ItemGroup>

</Project>
